print("Welcome to the Interactive Personal Data Collector!")
print("\n")
name=input("Please enter your name:")
age= int (input("Please enter your age:"))
height= float (input("Please enter your height in meters:"))
number= int (input("Please enter your favourite number:"))
print("\n")
print("Thank you! Here is the information we collected:")
print("\n")
print("Name :",name,"(Type : ",type(name),", Memory Address : ",id(name),")")
print("Age :",age,"(Type : ",type(age),", Memory Address : ",id(name),")")
print("Height :",height,"(Type : ",type(height),", Memory Address : ",id(name),")")
print("Favourite Number :",number,"(Type : ",type(number),", Memory Address : ",id(name),")")
print("\n")

birth_year= (2025-age)
print("Your birth year is approximately:",birth_year,"(based on your age of",age,")")
print("\n")
print("Thank you for using the Personal Data Collector. Goodbye!")
